// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ **Web Configuration (For Running on Chrome)**
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvDDkfNXacWCGIArJzMpG7b0Nq6xePN0',
    appId: '1:827161747707:android:7ce172d7c875e031c6105e',
    messagingSenderId: '827161747707',
    projectId: 'miniprojects6',
    authDomain: 'miniprojects6.firebaseapp.com',
  );

  // ✅ **Android Configuration (For Running on Android Emulator/Device)**
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvDDkfNXacWCGIArJzMpG7b0Nq6xePN0',
    appId: '1:827161747707:android:7ce172d7c875e031c6105e',
    messagingSenderId: '827161747707',
    projectId: 'miniprojects6',
  );

  // ✅ **iOS Configuration (Optional, You Don't Need It Now)**
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvDDkfNXacWCGIArJzMpG7b0Nq6xePN0',
    appId: '1:827161747707:android:7ce172d7c875e031c6105e',
    messagingSenderId: '827161747707',
    projectId: 'miniprojects6',
  );

  // ✅ **MacOS Configuration (Optional, You Don't Need It Now)**
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvDDkfNXacWCGIArJzMpG7b0Nq6xePN0',
    appId: '1:827161747707:android:7ce172d7c875e031c6105e',
    messagingSenderId: '827161747707',
    projectId: 'miniprojects6',
  );
}
